### ISSUE TITLE
[Update] /main 아이콘 이미지 적용하기 

### ISSUE THREAD

**Issue by ssssujini99** [dnd-side-project/dnd-7th-4-backend#88]
- [x] 대기상태 아이콘 url 적용하기
- [x] 체감온도 아이콘 url 적용하기

**Comment by chea-young** [comment]
![image](https://user-images.githubusercontent.com/63410509/185806704-f88a9ef9-8225-4958-bd2b-ec689f4d4ab2.png)
![image](https://user-images.githubusercontent.com/63410509/185806717-a151d201-587b-4ec9-8d5c-bbe95e1aadae.png)
